///////////////////////////////////////////////////////////
//  IGeneratorBehaviour.cs
//  Implementation of the Class IGeneratorBehaviour
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:14
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public interface IGeneratorBehaviour
    {

        Mask Generate();
	}

}