///////////////////////////////////////////////////////////
//  AsymmetryGeneratorBehaviour.cs
//  Implementation of the Class AsymmetryGeneratorBehaviour
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:12
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{

	public class AsymmetryGeneratorBehaviour : IGeneratorBehaviour
    {

		public AsymmetryGeneratorBehaviour()
        {

		}

		public Mask Generate()
        {

			return null;
		}

	}

}