///////////////////////////////////////////////////////////
//  ImageModel.cs
//  Implementation of the Class ImageModel
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:15
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{

	public class ImageModel : IPixelContainer
    {

		public List<Pixel> Pixels { get; set; } 

		public ImageModel()
        {

		}

		public ImageModel ApplyMask(Mask mask)
        {

			return null;
		}

		public int Sum()
        {

			return 0;
		}

    }

}