///////////////////////////////////////////////////////////
//  IPixelContainer.cs
//  Implementation of the Class IPixelContainer
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:16
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public interface IPixelContainer
    {

        int Sum();

    }

}