///////////////////////////////////////////////////////////
//  MaskPixel.cs
//  Implementation of the Class MaskPixel
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:19
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class MaskPixel
    {

		public int Value { get; set; } 
		public int X { get; set; } 
		public int Y { get; set; } 

		public MaskPixel()
        {

		}


	} 

} 