///////////////////////////////////////////////////////////
//  MaskPixel.cs
//  Implementation of the Class MaskPixel
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:19
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class MaskPixel
    {

		public int Value { get; } 
		public int X { get; } 
		public int Y { get; } 

		public MaskPixel(int x, int y, int value)
		{
			Y = y;
			X = x;
			Value = value;
		}

    } 

} 