///////////////////////////////////////////////////////////
//  MaskGenerator.cs
//  Implementation of the Class MaskGenerator
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:18
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class MaskGenerator
    {

		public IGeneratorBehaviour GeneratorBehaviour { get; set; } 

		public MaskGenerator()
        {

		}

		public Mask Generate()
        {

			return null;
		}

	}

}