///////////////////////////////////////////////////////////
//  Mask.cs
//  Implementation of the Class Mask
//  Generated by Enterprise Architect
//  Created on:      20-���-2019 10:46:17
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;


namespace Domain
{
	public class Mask
    {
	    public Mask(List<MaskPixel> pixels)
	    {
		    Pixels = pixels;
	    }

        public List<MaskPixel> Pixels { get; }

        public int Sum() => Pixels.Sum(x => x.Value);

        public int this[int index1, int index2] =>
			Pixels.Single(it => it.X == index1 && it.Y == index2).Value;
    }

}