///////////////////////////////////////////////////////////
//  Pixel.cs
//  Implementation of the Class Pixel
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:20
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class Pixel {

		public int Color { get; set; } 
		public int X { get; set; } 
		public int Y { get; set; } 

		public Pixel()
        {

		}

	}

}