///////////////////////////////////////////////////////////
//  Pixel.cs
//  Implementation of the Class Pixel
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:20
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class Pixel {

		public int Color { get; } 
		public int X { get; } 
		public int Y { get; } 

		public Pixel(int x, int y, int color)
		{
			Y = y;
			X = x;
			Color = color;
		}

	}

}