///////////////////////////////////////////////////////////
//  RandomGeneratorBehaviour.cs
//  Implementation of the Class RandomGeneratorBehaviour
//  Generated by Enterprise Architect
//  Created on:      20-окт-2019 10:46:21
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class RandomGeneratorBehaviour : IGeneratorBehaviour
    {

		public RandomGeneratorBehaviour()
        {

		}

		public Mask Generate()
        {

			return null;
		}

	}

}