///////////////////////////////////////////////////////////
//  SymmetryGeneratorBehaviour.cs
//  Implementation of the Class SymmetryGeneratorBehaviour
//  Generated by Enterprise Architect
//  Created on:      20-���-2019 10:46:22
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class SymmetryGeneratorBehaviour : IGeneratorBehaviour
    {
	    public Mask Generate()
        {

			return null;
		}

	} 

} 