///////////////////////////////////////////////////////////
//  SymmetryGeneratorBehaviour.cs
//  Implementation of the Class SymmetryGeneratorBehaviour
//  Generated by Enterprise Architect
//  Created on:      20-���-2019 10:46:22
//  Original author: Heln
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;


namespace Domain
{
	public class SymmetryGeneratorBehaviour : IGeneratorBehaviour
    {
	    public Mask Generate()
        {
            int x = 2;
            int y = 2;
            int numberOfColumns = 5;
            int maxValue = 100;
            int minValue = -30;

            Random rnd = new Random();
            List<MaskPixel> pixels = new List<MaskPixel>();

            for (int i = 0; i < (numberOfColumns / 2) + 1; i++)
            {
                for (int j = 0; j < i + 1; j++)
                {
                    int rndNumber = rnd.Next(minValue, maxValue);
                    if (i != x || j != y)
                    {
                        pixels.AddRange(new List<MaskPixel>
                        {
                            new MaskPixel(i, j, rndNumber),
                            new MaskPixel(numberOfColumns - i - 1, numberOfColumns - j - 1, rndNumber)
                        });
                        if (i != numberOfColumns - i - 1 && j != numberOfColumns - j - 1)
                        {
                            pixels.AddRange(new List<MaskPixel>
                            {
                                new MaskPixel(numberOfColumns - i - 1, j, rndNumber),
                                new MaskPixel(i, numberOfColumns - j - 1, rndNumber)
                            });
                        }
                        if (i != j)
                        {
                            pixels.AddRange(new List<MaskPixel>
                            {
                                new MaskPixel(j, i, rndNumber),
                                new MaskPixel(numberOfColumns - j - 1, numberOfColumns - i - 1, rndNumber)
                            });
                            if (i != numberOfColumns - i - 1 && j != numberOfColumns - j - 1)
                            {
                                pixels.AddRange(new List<MaskPixel>
                                {
                                    new MaskPixel(numberOfColumns - j - 1, i, rndNumber),
                                    new MaskPixel(j, numberOfColumns - i - 1, rndNumber)
                                });
                            }
                        }
                    }
                    else if (i == x && j == y)
                    {
                        pixels.Add(new MaskPixel(i, j, rndNumber));
                    }
                }
            }
            List<MaskPixel> maskPixels = new List<MaskPixel>();
            maskPixels.AddRange(pixels.Select(it => new MaskPixel(it.X - x, it.Y - y, it.Value)));

            return new Mask(maskPixels);
		}
    }
} 